### ISSUE TITLE
[Homework 1] 學習歷程

### ISSUE THREAD

**Issue by hchbiggrass** [coding-coworking-club/advanced-python-2020-fall#11]
## 提交連結

https://judge.ccclub.io/status/83d126bacccef30e0501e38349653f1b
## 程式碼

```python

```

## 錯誤訊息

Wrong Answer
## 問題描述

兩筆測資有過、自己想了六種情況都過，但仍然Wrong Answer。
我對於題目中給的兩筆測試資料的理解是：第一題是不對稱的結構，第二題是對稱結構但包含跟目標無關的課程
在第一題中，stats雖然沒有先修課程，但是和有先修的calculas放在同一階層
在第二題中，跟目標無關的課程不需要出現在學習歷程中

自己想的測試情況如下：
1. 目標課程a有三層先修課
a b
b c
c d
d
a
-> d c b a

2. 沒有任何課程是目標課程a的先修課
a
b c d
c d
d
a
-> a

3. 所有的課都是目標課程a的先修課
a b c d
b
c
d
a
-> b c d a

4. 目標課程b不是學習歷程的最高層
a b
b c d
c e
d
b
-> e c d b

5. 先修課程d同時是c和e的先修課
a b e
b c
e d
c d
a
-> d c b e a

6. 目標課程包含a和d
a b c
d e
c
e
a d
-> b c e a d

我真的想不到了，請提示我錯誤的測試資料，謝謝

**Comment by sam7k9621** [comment]
我猜你的問題可能是忽略這個 同一個層次的課程按字首字母順序排列
你可以試試看
a b c d
b f j
c g i
d e
g l
e k
a

->klefgijbcda

**Comment by hchbiggrass** [comment]
謝謝你的回覆，可是我輸入你給我的測資是OK的。不過我原本有把輸入行數限定在5，不知道是不是這個原因

**Comment by yeutong** [comment]
輸入行數限定五行是沒問題的，你可以試試看這筆測資
```
r l
a C J r j
L a
J b B
L
```
答案應該要是
```
B b l C J j r a L
```

**Comment by hchbiggrass** [comment]
謝謝你的回覆，這筆測資錯了，我早上再改

**Comment by hchbiggrass** [comment]
目前這題我已經解出來了，早上改好之後遇到run time error，我把程式碼盡量用list / dict comprehension節省步數就過了。這段話留給其他可能遇到類似問題的人。

**Comment by yeutong** [comment]
讚讚！
不過 `Run Time Error` 是因為執行時發生錯誤，可能是迴圈的終止條件沒寫好之類的。如果是超時的話會是 `Time Limit Exceed` 喲！
