### ISSUE TITLE
[Homework 2] 資料比對

### ISSUE THREAD

**Issue by sam7k9621** [coding-coworking-club/advanced-python-2020-fall#12]
## 程式碼

import re
def main():
    inputline = input().split()
    label_data = []
    while True:
        inputline = input().split("\t")
        if "raw-data.txt" in inputline:
            break

        label, sentence = inputline[:2]
        label_data.append( (label, sentence) )

    raw_data, raw_data_fixed = [], []
    while True:
        try:
            inputline = input()
            inputline_fixed = " ".join( re.sub(r'[^\w]', ' ', inputline).lower().split() )
            raw_data.append( inputline )
            raw_data_fixed.append( inputline_fixed )
        except:
            break

    for l, d in label_data:
        try:
            idx = raw_data_fixed.index( d )
            print( "{}\t{}".format( l, raw_data[idx] ) )
        except:
            print( "{}\t{}".format( l, d ) )

if __name__ == '__main__':
    main()

```python

```

## 錯誤訊息

Wrong Answer

## 問題描述

想請問範例中的 Kevin's Artis is very...large...
假設他會在label-data.tsv 裡面出現，那他出現的形式會是 kevin s Artis is very large
還是會是kevin's Artis is very large?
又label-data.tsv 裡面所出現的句子是單純以一個空格所區分嗎？

**Comment by sam7k9621** [comment]
沒有成功附上連結
我的嘗試連結在這
https://judge.ccclub.io/status/ffd3e73ad80f36ffe26f8c132f39c6fa

**Comment by yeutong** [comment]
其實應該可以直接編輯新增提交連結，然後關於你的疑問：
1. `Kevin's Artis is very...large...` 若有在處理後的資料中出現，會是`kevins artis is verylarge`這樣的形式
2. label-data.tsv 裡面所出現的句子不一定以一個空格區分

**Comment by sam7k9621** [comment]
label-data.tsv 裡面所出現的句子不一定以一個空格區分

如果是這樣那以下的測資會怎麼處理？
case1

label-data.tsv
label__1	i am a                  good boy
raw-data.txt
I am a good boy!!!

case2
label-data.tsv
label__1	i am a  good boy
raw-data.txt
I am a               good boy!!!

因為看起來多餘的空格是不會被移除掉也不算是特殊符號對吧？

**Comment by yeutong** [comment]
對的，有新增範例三在 judge 了，應該會比較清楚～
