### ISSUE TITLE
[Homework 1] 小明撿破爛

### ISSUE THREAD

**Issue by hchbiggrass** [coding-coworking-club/advanced-python-2020-fall#15]
## 提交連結

https://judge.ccclub.io/status/8473853b81c4cac17e9ea854bf1dad7b
## 程式碼

```python

```

## 錯誤訊息

Wrong Answer
## 問題描述

題目提供的兩個測資有過，自己想了4種情況，跑出來和手算一致，需要找出錯誤的測資。

#完全不用拆
10
1 2 3 4 5 6 7 8 9 10
1 2 3 4 5 6 7 8 9 100
-> 100

#拆到1最好
8
1 2 3 4 5 6 7 8
10 2 3 4 5 6 7 8
-> 80

#不同長度但同價格(很多層)
8
1 2 3 4 5 6 7 8
5 2 3 4 5 6 7 8
-> 40

#全部同樣價格
5
1 2 3 4 5
5 5 5 5 5
->25

**Comment by sam7k9621** [comment]
試試看這個？
8
1 2 3 4 5 6 7 8
0 7 3 4 5 29 35 8
-> 36

**Comment by hchbiggrass** [comment]
謝謝你的回覆，這個測試資料我跑出來也是36

**Comment by AtomBlack** [comment]
我也是 但也是 runtime error

**Comment by yeutong** [comment]
試試看這個
```
16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
7 1 19 12 6 16 13 19 1 15 9 5 12 20 10 6
```
輸出應該是112

**Comment by AtomBlack** [comment]
我輸出是112
 但我還是一職出現Runtime error

**Comment by hchbiggrass** [comment]
助教，我用手算是2X(19+19+14)=104耶，我完全無法理解為什麼答案會是112。我的詳細拆解如下:
16<-8+8
8<-5+3
5<-3+2
3<-3+0
2<-1+1
其中一邊的8最後會變成1+1、3+0、3+0，所以是14+19+19。
由於有兩個8，因此再X2，就是2X(14+19+19)=104

**Comment by hchbiggrass** [comment]
我想通了，3可以分成1+1+1。
