### ISSUE TITLE
[Homework 2] 緊急避難系統

### ISSUE THREAD

**Issue by sam7k9621** [coding-coworking-club/advanced-python-2020-fall#20]
## 程式碼

```python

```

## 錯誤訊息

Memory/Time Limit Exceeded

## 問題描述

這題是限制只能使用built-in library作答嗎（不能使用numpy ）？
我使用的2d list 會超過記憶體上限
如果list搭配array.array 反而是時間會超過上限
不知道能不能給點方向或是提示

**Comment by hyusterr** [comment]
不用使用套件也可以過這題，別擔心。
可以想想看怎麼樣用 dictionary 來節省時間！
