### ISSUE TITLE
[Homework 2] 超商取貨

### ISSUE THREAD

**Issue by b04310041** [coding-coworking-club/advanced-python-2020-fall#21]
## 提交連結

https://judge.ccclub.io/contest/5/problem/203401

## 程式碼

```python

phone_name_product = []
phone = []
name = []
product = []

while True:
    lst = input().split(",")
    if lst == ["end"]:
        break
    else:
        phone_name_product.append(lst)
        phone.append(lst[0][7] + lst[0][8] + lst[0][9])
        name.append(lst[1])
        product.append(lst[2])

final_answer = []
while True:
    try:
        search = input().split()

        ph = search[0]
        search.pop(0)
        na = " ".join(search)

        # ph = search[0]
        # na = search[1]

        is_there_product = []
        for i in range(len(phone)):
            if (ph == phone[i]) and (na == name[i]):
                # print(product[i])
                final_answer.append(product[i])
                is_there_product.append(i)
                break
        if is_there_product == []:
            # print("Check again!")
            final_answer.append('Check again!')
    except:
        break

# print(final_answer)
for i in range(len(final_answer)):
    print(final_answer[i])

```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

原本 wrong answer 後來發現是沒有考慮到名字可能有空格的情形，所以把 try 裡面那兩行註解，換成了註解上面的三行 code，結果就變成了 Time Limit Exceeded，測資結果是正確的，while 迴圈裡面的 try except 用法也跟其他習題的用法一樣，不知道是不是漏考慮了什麼ＱＱ
感謝助教

**Comment by hyusterr** [comment]
如果用 list 來存取資料會超出時間上限的話，有沒有考慮過用 dictionary 呢？

**Comment by b04310041** [comment]
phone = []
name = []
product = []

while True:
    lst = input().split(",")
    if lst == ["end"]:
        break
    else:
        phone.append(lst[0][7] + lst[0][8] + lst[0][9])
        name.append(lst[1])
        product.append(lst[2])

final_answer = {}
count = 0
while True:
    try:
        search = input().split()

        ph = search[0]
        search.pop(0)
        na = " ".join(search)

        # ph = search[0]
        # na = search[1]

        is_there_product = []
        for i in range(len(phone)):
            if (ph == phone[i]) and (na == name[i]):
                # print(product[i])
                final_answer[count] = product[i]
                is_there_product.append(i)
                break
        if is_there_product == []:
            # print("Check again!")
            final_answer[count] = 'Check again!'
        count += 1
    except:
        break

# print(final_answer)
for i in range(len(final_answer)):
    print(final_answer[i])

感謝助教回覆
上面是 變成以字典存的 code，不過這樣還是 Time Limit Exceeded，想請問是不是 key 用 count 每次加 1 導致的，如果是的話可否給點小提示 >< 感謝助教

**Comment by b04310041** [comment]
感謝助教回覆
變成以字典存，但還是 Time Limit Exceeded，想請問是不是 key 用 count 每次加 1 導致，如果是的話可否給一點提示><
感謝助教～

```

phone = []
name = []
product = []

while True:
    lst = input().split(",")
    if lst == ["end"]:
        break
    else:
        phone.append(lst[0][7] + lst[0][8] + lst[0][9])
        name.append(lst[1])
        product.append(lst[2])

final_answer = {}
count = 0
while True:
    try:
        search = input().split()

        ph = search[0]
        search.pop(0)
        na = " ".join(search)

        # ph = search[0]
        # na = search[1]

        is_there_product = []
        for i in range(len(phone)):
            if (ph == phone[i]) and (na == name[i]):
                # print(product[i])
                final_answer[count] = product[i]
                is_there_product.append(i)
                break
        if is_there_product == []:
            # print("Check again!")
            final_answer[count] = 'Check again!'
        count += 1
    except:
        break

# print(final_answer)
for i in range(len(final_answer)):
    print(final_answer[i])

```

**Comment by yeutong** [comment]
你現在是用 dictionary 來存配對好的取貨人資訊，可以想想看在存進貨資訊的時候能不能也用 dictionary 來處理
小提示：dictionary 的 key 不一定只能是 string 或 integer

**Comment by b04310041** [comment]
謝謝助教ＱＱ
解決了！！！
