### ISSUE TITLE
[General] 作業二Input為非固定行數

### ISSUE THREAD

**Issue by wateroctopus** [coding-coworking-club/advanced-python-2020-fall#3]
## 提交連結

作業二 手拉手團康遊戲
https://judge.ccclub.io/contest/5/problem/203404

作業二 超商取貨
https://judge.ccclub.io/contest/5/problem/203401

## 問題描述

想問一下，因為之前作業題目的Input皆是一行一行輸入，通常會在開頭給預計Input的行數，或者設計成有結束的方式(像是輸入end等)。
但是像是作業二的手拉手團康遊戲或是超商取貨(題目後半)等題目，皆未有固定行數的設計。
所以想問我們撰寫的程式碼，需要設計成一次可以多行的Input(之前沒有寫過)，還是要讓Input可以無限輸入，輸入一次給予一次Output呢？

**Comment by yeutong** [comment]
這個的確沒有特別教過，但使用上蠻方便的
可以查查看例外處理的 `EOFError` (End-Of-File Error) 怎麼用，讓程式讀入不定行~

**Comment by wateroctopus** [comment]
謝謝。 只是題目沒有說什麼時候輸入結束開始輸出Output的話，不知道什麼時候讓它開始print答案耶？

**Comment by yeutong** [comment]
output 的時機沒有影響~ 不管是邊讀入資料邊 print 或最後全部一起 print，只要整個輸出內容與測資答案一致就 OK ！

**Comment by hyusterr** [comment]
可以考慮用
https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-613b2fdf38bf
裡面提到的第三種方式測試你的程式

**Comment by wateroctopus** [comment]
了解了，非常感謝！ 我思考一下練習用其他方式檢視測資～ 作業二[超商取貨]最後真的是處理EOFError時就可以Accept了，不知道是因為測資有非題目格式的輸入，還是因為程式讀入不定行所造成的，之前一直出現Runtime Error
> output 的時機沒有影響~ 不管是邊讀入資料邊 print 或最後全部一起 print，只要整個輸出內容與測資答案一致就 OK ！

謝謝！這篇真是受用無窮，雖然很多沒學過需要嘗試
> 可以考慮用
> https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-613b2fdf38bf
> 裡面提到的第三種方式測試你的程式

**Comment by wateroctopus** [comment]
> 了解了，非常感謝！ 我思考一下練習用其他方式檢視測資～ 作業二[超商取貨]最後真的是處理EOFError時就可以Accept了，不知道是因為測資有非題目格式的輸入，還是因為程式讀入不定行所造成的，之前一直出現Runtime Error
> 
> > output 的時機沒有影響~ 不管是邊讀入資料邊 print 或最後全部一起 print，只要整個輸出內容與測資答案一致就 OK ！
> 
> 謝謝！這篇真是受用無窮，雖然很多沒學過需要嘗試
> 
> > 可以考慮用
> > https://medium.com/ccclub/ccclub-python-for-beginners-tutorial-613b2fdf38bf
> > 裡面提到的第三種方式測試你的程式
