### ISSUE TITLE
[Homework 2] 資料比對

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/advanced-python-2020-fall#34]
## 提交連結

https://judge.ccclub.io/status/875df3ffe4c511ba110905b9bab7511e

## 程式碼

```
import re
dic={}
code={}
c=0
while True:
    s=input()
    if "\t" in s:
        label,string=s.split("\t")
        stick=string.replace(" ","")
        s=s.split("\t")+[stick]
        dic[c]=s
    c+=1

    if s=="raw-data.txt":
        break

while True:
    try:
        s=input()
    except EOFError:
        break
    else:
        trans=re.sub(r'[^\w]', ' ', s).replace(" ","").lower()
        code[trans]=s
for d in dic:
    stick=dic[d][-1]
    lower=dic[d][-2]
    label=dic[d][-3]
    if stick in code:
        print(label+"\t"+code[stick])
    else:
        print(label+"\t"+lower)

```

## 錯誤訊息

Wrong Answer 

## 問題描述

第一個while True製作出字典dic，紀錄label-data.tsv的情形，與轉小寫句子沒空格的string，以便比對亂碼。以範例一為例，dic呈現如下:
{1: ['label__1', 'i am a good boy', 'iamagoodboy'], 2: ['label__0', 'i am a bad boy', 'iamabadboy'], 3: ['label__1', 'i am a good girl', 'iamagoodgirl']}

第二個while True製作字典code，紀錄亂碼情形。亂碼為字典code的值，字典的鍵為亂碼轉小寫沒空格的string。以範例一為例，code呈現如下:
{'iamagoodboy': 'I am a good boy!!!', 'iamagoodgirl': 'I: am a good girl#$%^&?!', 'youshouldseethesea': 'You should see THE SEA!', 'kevinsartisisverylarge': "Kevin's Artis is very...large..."}

兩個while True結束後，便開始比對兩個字典dic&code。若dic的值(第三個值，亦即轉小寫句子沒空格的string)，出現在code裡面，表示有找到原始亂碼；若沒出現在code裡，表示沒找到原始亂碼。

上述方式可以成功解決三個範例，為何測資是Wrong Answer ? 請助教提點，謝謝。

**Comment by Neptune2901** [comment]
\w的使用會讓底線沒被當符號處理掉唷！
https://docs.python.org/3.2/library/re.html

**Comment by alemapnil** [comment]
[https://judge.ccclub.io/status/f3948a9207a9f70e1092719ff9694f96](url)

針對底線部分，我添加了replace("_","")，
另外針對空格情況，也做了\s處理，

為何還是過不了? 請助教詳細指教，麻煩了

**Comment by yeutong** [comment]
嗨~ 題目中所說的處理後的資料是將符號去除，並全部轉成小寫，沒有包含把空格去除。你這樣處理的話比對上可能會出錯，舉例來說：如果 raw data 裡面只有 `thankyou!`，該筆資料處理後應該會是 `thankyou`，同時 label data 裡面如果出現 `thank you`，這兩筆資料不應該成功比對在一起。

**Comment by alemapnil** [comment]
[https://judge.ccclub.io/status/27e2ac2153457c49f1f0031387fb511b](url)

針對助教舉例的 `thank you` 情況，我有修改正規表示法，為何還是不給過?  
請助教提點，謝謝

**Comment by yeutong** [comment]
你這個版本忘記處理底線了

**Comment by alemapnil** [comment]
我有處理底線阿，底下例子就順利印出output--->label__2        thank __you!!

label-data.tsv
label__2        thank you
raw-data.txt
thank __you!!
^Z
label__2        thank __you!!

**Comment by yeutong** [comment]
剛剛點錯連結了不好意思，底線沒問題
想問 strip() 的用意為何？

**Comment by alemapnil** [comment]
謝天謝天終於過了，謝謝 @tong4627  的即時回覆
