### ISSUE TITLE
[Homework 2] 緊急避難系統

### ISSUE THREAD

**Issue by yichensu** [coding-coworking-club/advanced-python-2020-fall#41]
## 提交連結

https://judge.ccclub.io/status/85b64cf73a5c4f6f2f261c5209568011

## 程式碼

```python
import math

limit = int(input())
distance = int(input())
people = int(input())
       
data = {}
while people > 0:
    k, *v = input().split()
    data[k] = [int(j) for j in v]
    people -= 1
      
site_num = int(input())
site = {}
while site_num > 0:
    k, *v = input().split()
    site[k] = [int(j) for j in v]
    site_num -= 1
      
for i in data:
    result = []
    for j in site:
        if distance > math.sqrt((data[i][0] - site[j][0])**2 + (data[i][1] - site[j][1])**2):
             result.append(j)
    if len(result) > 0:
        print(i+" "+" ".join(result))
    else:
        print(i+" "+'byebye')
```

## 錯誤訊息

<img width="281" alt="Screen Shot 2020-10-13 at 11 32 06 PM" src="https://user-images.githubusercontent.com/56100559/95882483-55cd8380-0dac-11eb-84de-9611302eac71.png">

## 問題描述

已經遵照皆以dict實作，目前仍需要兩倍時間，思考命名變數與其他操作似乎皆必要，好奇優化建議

**Comment by yeutong** [comment]
你現在是檢查每一個人相對於每一個避難所的距離，如果有 100 個人，100 個避難所，這樣你就要做接近 100 * 100 次檢查才能找到答案。可以想想看能不能做一些預處理。例如把地圖切成一些區塊，這樣每個人就只要查找他所在區塊及周圍區塊的避難所是不是在逃跑距離內就好。

**Comment by yeutong** [comment]
然後標題記得改一下喲~
