### ISSUE TITLE
[Homework 3] 資料處理方式確認

### ISSUE THREAD

**Issue by riversound520** [coding-coworking-club/advanced-python-2020-fall#51]
## 提交連結
無

## 程式碼
無

```python

```

## 錯誤訊息
無

## 問題描述

關於資料處理的一些定義與To Do，想跟助教確認一下

- **Q1**--步驟5、調整 Loan Title 項目
**描述**：移除 loan title 中，數目小於等於 10,000 的組別，以及組別為' '的組
**問題**：意思是，只要此內容 (例如：'For Justin.')在全部loan title欄位的出現次數小於1萬次，就將'For Justin.'移除並"設為空"嗎?  (因為目前檢視了前50筆Rejected資料，loan title內容都還蠻獨一無二的)

- **Q2**--步驟7、去掉有空值的資料列
**描述**：請各列中含有空值(NA)的資料拋棄
**問題**：是否僅需將該列的空值(NA)移除即可，不需要將整列刪除?

以上再麻煩助教解惑了，謝謝!

**Comment by k1012ken** [comment]
藉此討論串同樣想請教助教們有關  Loan Title 之資料處理問題。

假如 Loan Tiltle 裡的分組有 Debt consolidation 以及  debt_consolidation ，或者為 Other  以及 other 。
是否需要將前述兩種分組視為同一組。

不太確定上述對最終解答有沒有影響。

(已請教助教，這部份本次不用處理）
