### ISSUE TITLE
[Homework 1] 小明撿破爛

### ISSUE THREAD

**Issue by alemapnil** [coding-coworking-club/advanced-python-2020-fall#9]
## 程式碼

```

import itertools as it

s1=int(input())
s2=[int(i) for i in input().split(" ")]
s3=[int(i) for i in input().split(" ")]
dic={}

#將每段每公尺對應的價格做成字典
for i in range(len(s2)):
    dic[s2[i]]=s3[i]


largest=[]

#在s2中抓取加總為s1的全部可能
for n in range(1, len(s2)+ 1):
    for combination in it.combinations_with_replacement(s2, n):
        if sum(combination) == s1: # combination is tuple. (1, 2, 2, 2)
            c=0
            #計算該組合可兌換之價格
            for num in combination:  #num is 1,2,2,2
                c+=dic[num]
            largest.append(c)
            #將價格丟到列表去一個個比大小，留下較大值，最後比出最大值
            largest=sorted(largest,reverse=True)
            largest=largest[0:1]
            c=0
print(max(largest))

```

## 錯誤訊息

Time Limit Exceeded 

## 問題描述

兩個例題都有計算出來，但側資顯示Time Limit Exceeded
因為畢竟每公尺對應價格不同，也沒有邏輯可言，所以還是必須要計算所有組合的對應價格，取最大值
我只生成一個列表，同時該列表始終放入一個值而已，為何還是不給過?
若這方法助教覺得不妥當，可否請助教稍微透漏其他種思考切入方式?
謝謝

**Comment by jeffery12697** [comment]
這題考的是ＤＰ，我隨便 google 的[資料](http://web.ntnu.edu.tw/~algo/DynamicProgramming.html)，你可以再用關鍵字找一些

**Comment by tong4627** [comment]
@alemapnil  請參考 [GitHub 使用教學](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29) 補上提交連結喲

**Comment by yeutong** [comment]
請參考[學員須知](https://www.notion.so/GitHub-Issue-912d246f45f9462e89b9ab1d9c3c8d29)附上提交連結喲

你的解題邏輯是對的，這樣的確可以算出答案，唯一的問題是當數字稍微大的時候，就會很花時間。像是你測長度 10 的測資，應該可以瞬間出現答案，但到長度 15 就需要等上頗久（我測是大約要一分鐘）。這題的測資沒有要刁難大家，我記得最大的應該是 20 公尺左右。
你可以想想看要怎麼避免計算那些絕對不可能的組合，例如長度是 5 時，`(5, 5, 5, 5)`、`(5, 4, 3, 3)` 等就其實可以略過不要算，看看有沒有辦法進一步節省時間。
除此之外，最後所有可能的組合中（也就是符合 `sum(combination) == s1`）的長度組合，是不是有些可以不用考慮呢？舉例來說，若長度是 5，你比較了 `(2, 2, 1)` 跟 `(2, 3)` 之後，發現 `(2, 2, 1)` 的組合能帶來較高價值。這就隱含著凡是長度為 3 的某段鋼筋，若切成 2 + 1 會更好。因此接下來你就不需計算 `(1, 1, 3)` 的組合有多少價值，而應該把 3 切開，直接算 `(1, 1, 1, 2)` 的價值就好。也就是說，你可以先算好長度為 3 的鋼筋要如何切割才會有最大的價值（3 或 2+1 或1+1+1），之後遇到包含長度為 3 的組合就可以直接套入
可以想想看要怎麼比較有系統的來做到這件事~

**Comment by alemapnil** [comment]
s1=int(input())
s2=[int(i) for i in input().split(" ")]
s3=[int(i) for i in input().split(" ")]

s2.insert(0,0)
s3.insert(0,0)

dic={}

for i in list(zip(s2,s3)):
   dic[i[0]]=i[1]


def F(n):
   if n==1:
      return dic[1]
   elif n==2:
      a=max([dic[1]+dic[1],dic[2]])
      return a
   elif n==3:
      a=max([F(2)+F(1),dic[3]])
      return a 
   elif n==4:
      a=max([F(2)+F(2),F(3)+F(1),dic[4]])
      return a 

print(F(4))

我現在想要做一個類似費氏數列的東西，就是將前面長度對應的最高價格記錄下來，以後不用重複計算。但我發現最後還是要計算所有排列組合，才可算得出來。例如n==5，就要把加總為5的組合算出並取最大值，但總不可能將所有數值1~7對應最大值寫出，所以請問助教這方面是要如何突破?

**Comment by alemapnil** [comment]
```
s1=int(input())
s2=[int(i) for i in input().split(" ")]
s3=[int(i) for i in input().split(" ")]

s2.insert(0,0)
s3.insert(0,0)

dic={}

for i in list(zip(s2,s3)):
   dic[i[0]]=i[1]


def F(n):
   if n==1:
      return dic[1]
   elif n==2:
      a=max([dic[1]+dic[1],dic[2]])
      return a
   elif n==3:
      a=max([F(2)+F(1),dic[3]])
      return a 
   elif n==4:
      a=max([F(2)+F(2),F(3)+F(1),dic[4]])
      return a 
   
   return F(n-1)+F(1)
print(F(7))
```
我現在想要做一個類似費氏數列的東西，就是將前面長度對應的最高價格記錄下來，以後不用重複計算。但我發現最後還是要計算所有排列組合，才可算得出來。例如n==5，就要把加總為5的組合算出並取最大值，但總不可能將所有數值1~7對應最大值寫出，所以請問助教這方面是要如何突破?
